### ISSUE TITLE
Cannot choose a contact as a controller account

### ISSUE THREAD

**Issue by DemiMarie-parity** [polkadot-js/apps#3021] opened 2020-06-21 20:08 UTC
When setting up a new stash account, the UI does not offer contacts as possible controller accounts.  Manually pasting the desired address is unreliable ― it often gets overwritten before the actual transaction is submitted.

(In my case, the secret key to the contract account is on a special-purpose Ledger device.  But PolkadotJS cannot know that.)

**Comment by jacogr** [comment] 2020-06-22 05:09
Duplicate of https://github.com/polkadot-js/apps/issues/1566

If you want to do it, you can send the txs manually via the extrinsics tab. Having UI support (apart from displaying in account actions) is probably not something that will happen soon - people mess up enough.

PS: Ledger is supported (once enabled in settings).

**Closed by jacogr** 2020-06-22 05:09 UTC
Labels: <duplicate>

**Comment by DemiMarie-parity** [comment] 2020-06-22 17:21
@jacogr how does this work?  I can’t find any mention of Ledger in the settings.

**Comment by jacogr** [comment] 2020-06-22 17:56
It is only enabled on Kusama.

![image](https://user-images.githubusercontent.com/1424473/85319809-663ab500-b4c2-11ea-928f-daf5542a40f5.png)

Once the next release of `@zondax/ledger-polkadot` hits, these 2 PRs for can be merged which will enable Polkadot -

- https://github.com/polkadot-js/ui/pull/332
- https://github.com/polkadot-js/apps/pull/3022

Awaiting the updated release from Zondax for Polkadot & Kusama later today.

**Comment by DemiMarie-parity** [comment] 2020-06-22 22:50
I am on Kusama :)

**Comment by jacogr** [comment] 2020-06-23 05:03
1. switch the last setting to WebUsb above
2. the Accounts page will have a „Query Ledger“ Option now to discover/attach
