### ISSUE TITLE
Fee calculation not correct for contract.create

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#1165] opened 2019-05-15 01:44 UTC
![Screen Shot 2019-05-15 at 1 42 12 PM](https://user-images.githubusercontent.com/1201310/57742969-49587d80-7717-11e9-8a7b-6b603de37e09.png)

Endowment value of 1G should be included. Also gas limit X gas price.

Is it even possible to correctly calculate how much money is required in order to ensure a success transaction for all the transaction type?

**Comment by jacogr** [comment] 2019-05-15 05:28
Yes, still on the list - duplicate of #983

**Closed by jacogr** 2019-05-15 05:28 UTC
