### ISSUE TITLE
Uncaught error. Chrome browser Version 108.0.5359.125 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by LaplaceTransformS** [polkadot-js/apps#8588] opened 2022-12-20 17:26 UTC
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment] 2022-12-21 05:31
In which area, which chain, what data?

**Comment by LaplaceTransformS** [comment] 2022-12-21 11:32
> In which area, which chain, what data?

Staking Overview via the graph icon using either Parity or OnFinality.  Also via the Staking / Validator Stats tab using a validator address in the query.  The graphs don't paint and the exception is thrown.

**Comment by jacogr** [comment] 2022-12-21 13:28
Which chain?

**Comment by LaplaceTransformS** [comment] 2022-12-21 14:06
Oh, sorry: Polkadot.

**Comment by jacogr** [comment] 2022-12-21 14:18
Any specific Polkadot validator? As an example, this one is all ok for me https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/staking/query/1REAJ1k691g5Eqqg9gL7vvZCBG7FCCZ8zgQkZWd4va5ESih (clicked through on a random)

If the above is not ok, would appreciate all the text in the red box, that may yield ideas.

Best however if you have a specific one that does create issues that I can also use to replicate.

**Comment by LaplaceTransformS** [comment] 2022-12-21 14:47
That one, and all others fail from the Overview page.  Which confirms it's likely a local issue.

Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'enabled')

TypeError: Cannot read properties of undefined (reading 'enabled')
at Object.afterDraw (https://polkadot.js.org/apps/main.4f600e68.js:2:2306659)
at h (https://polkadot.js.org/apps/react.01.775885da.js:2:675140)
at Re._notify (https://polkadot.js.org/apps/react.01.775885da.js:2:602102)
at Re.notify (https://polkadot.js.org/apps/react.01.775885da.js:2:601891)
at rt.notifyPlugins (https://polkadot.js.org/apps/react.01.775885da.js:2:620514)
at rt.draw (https://polkadot.js.org/apps/react.01.775885da.js:2:616004)
at rt.render (https://polkadot.js.org/apps/react.01.775885da.js:2:615576)
at rt.update (https://polkadot.js.org/apps/react.01.775885da.js:2:613632)
at rt.<anonymous> (https://polkadot.js.org/apps/react.01.775885da.js:2:609215)
at rt._doResize (https://polkadot.js.org/apps/react.01.775885da.js:2:679585)

**Comment by jacogr** [comment] 2022-12-21 15:02
Ummm, so all graph related. 

Versions have not changed, however an additional plugin was added to all graphs, which would be the culprit it would seem. This is going to be a bit of a bastid to track down since it cannot be reproduced. However at least there is a starting point although it is not in apps code itself, but rather in a library used in the UI.

**Comment by LaplaceTransformS** [comment] 2022-12-21 17:13
I might be able to assist if the development tools can be set up easily on Win.  Not really a JavaScript developer but have c, c++ knowledge.  Also Linux platform sw environment is available.

**Comment by jacogr** [comment] 2022-12-22 13:41
Can you do me a favor -

- On either Kusama or Polkadot see if this graph works (linking to Kusama here - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/latency)

- On Kusama, expand either of the Referenda rows, e.g https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/referenda

Trying to see if the same issue applies to all graphs or just those on staking. 

(Still digging into the libs to see what could cause it, slightly more tricky when I cannot reproduce it - but as always, where there is smoke, there is fire)

**Comment by LaplaceTransformS** [comment] 2022-12-22 13:47
Bullet 1: Graphs work both on Polkadot and Kusama
Bullet 2: Expansion displays curves nicely!

**Comment by LaplaceTransformS** [comment] 2022-12-22 14:15
Curious that the validator stat graphs paint when the debugger is active.  Maybe a timing issue?  Also, checked Firefox which works, but I don't have the .js extension installed.

**Comment by jacogr** [comment] 2022-12-22 15:24
Thank you.

I will look at all the options passed through (between the graphs, working and non), maybe there is something weird in the graph options.

**Comment by jacogr** [comment] 2022-12-23 08:38
Could you just look again at the staking charts - with the last PR I made a small change (based on your comment that it quite possibly is timing related) where the charts would show while loading the data, which may help with the plugin initialization that causes this. 

I think your observation quite possibly points to the exact cause - staking is the only chart area where all the linked charts appear at different intervals. If the current version doesn't fix your issue, the next step would be to wait until all 4 charts have data and then draw them. (Which aligns with all the other charts in the UI)

... I still hate not-reproducable-on-my-side issues and certainly hate sending it to you to check without knowing 100%, but sadly this is where we are. So please bear with me, we will get it right.

**Comment by LaplaceTransformS** [comment] 2022-12-23 11:00
Your optimism is infectious.  You had my hopes up!  Unfortunately, the problem persists.  But thinking about timing, the exception is thrown immediately when the page loads.  As you know, when the page loads normally it takes some time to paint each graph.

**Comment by LaplaceTransformS** [comment] 2022-12-23 11:24
While on the overview page the first error message in the inspection debugger is: 

Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by jacogr** [comment] 2022-12-23 12:33
I'm not that optimistic - stumbling around in the dark and swearing a lot ... 

The last PR adds an extra error boundary to all charts, so that _might_ help with all flyouts not working. Notice the use of _might_ ...

**Comment by LaplaceTransformS** [comment] 2022-12-23 12:38
We're 75% there!
![Screenshot 2022-12-23 073814](https://user-images.githubusercontent.com/102182909/209337608-506ceccc-df58-48d1-ad8b-f96f5e2c9998.png)

**Comment by LaplaceTransformS** [comment] 2022-12-23 12:43
100%!
![Screenshot 2022-12-23 074217](https://user-images.githubusercontent.com/102182909/209338068-72fe0e2e-c399-417a-ad1f-ee47266de2a2.png)

**Comment by LaplaceTransformS** [comment] 2022-12-23 12:43
Bravo!

**Comment by jacogr** [comment] 2022-12-23 12:44
How did we get to 100%? That is weird, it should work or not work - not sometimes work 75% and then other times 100%...

**Comment by LaplaceTransformS** [comment] 2022-12-23 12:45
Hmmm.  Latency in the deployment?

**Comment by LaplaceTransformS** [comment] 2022-12-23 13:24
Thank you for all you do!  I'm good with the resolution.  Let me know if there is anything else you'd like to check before we close.

**Comment by jacogr** [comment] 2022-12-23 13:30
Let's keep this open for a short while - I'm just worried it may come back since I did make some rendering tweaks, however since this one was non-reproducable for me, I'm just worried that whatever the cause it may come back.

So if all ok in a week with no recurrences, will close it.

I really appreciate your patience here - this one was/is literally stumbling around in the dark.

**Comment by LaplaceTransformS** [comment] 2022-12-23 13:53
I appreciate the challenge of not being able to reproduce the fault locally.  I'm happy to help and for the education!  I've been looking  at the code changes you made and appreciate the insight.  I'm just wading in again with app dev after having been away for some time.  Enjoy any time off you may have coming over the holidays.  Cheers mate!

**Comment by jacogr** [comment] 2023-01-05 12:09
Going to close as of now since no new reports.

Thank you for all the effort leading the blind.

**Closed by jacogr** 2023-01-05 12:09 UTC
Labels: @react-components, -size-m, <needs investigation>

**Comment by LaplaceTransformS** [comment] 2023-01-05 18:27
👍
