### ISSUE TITLE
Add scrollbar for the nominator list

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#276] opened 2018-09-03 13:54 UTC
The more nominators you have the wilder the UI becomes:
![image](https://user-images.githubusercontent.com/738724/44990354-0db6c280-af91-11e8-93a0-c39d4ade6656.png)

I propose the following change to have the UI limited to the following no matter what:
![image](https://user-images.githubusercontent.com/738724/44990392-2921cd80-af91-11e8-8904-356672e918ec.png)

The code shows:
![image](https://user-images.githubusercontent.com/738724/44990413-35a62600-af91-11e8-8915-a03fc2b7d9e2.png)

I´d suggest:
- [ ] to encapsulate all the `div.ui--AddressMini padded` into a new div with class `ui--Nominators` in order to keep the button visible at all time
- [ ] Add the following pros to the new css of `ui--Nominators`
```
overflow-y: overlay;
max-height: 196px;
padding-right: 18px;
```

**Comment by jacogr** [comment] 2018-09-03 13:56
While in here, think we can also lose some space/padding between items. (From the screenshot it looks like quite a bit, just a 20% trim or so)

**Comment by chevdor** [comment] 2018-09-03 15:33
I agree, that would not hurt.

**Comment by jacogr** [comment] 2018-09-21 05:45
Cool. Lemme whip up something - I'm actually in the same position, local node or not. Basically it shows only for validators with a lot of nominators. But will figure something out to reproduce and then update.

**Comment by jacogr** [comment] 2018-09-21 07:51
Ok, I came up with a hack that at least shows the issue and allows for fixes. (Some dev hacking required). Basically I can make it do this -

<img width="526" alt="polkadot apps portal 2018-09-21 09-45-37" src="https://user-images.githubusercontent.com/1424473/45867223-3c9ba980-bd83-11e8-915b-5907e9cadc2c.png">

So to get this working you need to have nominated somebody on the poc-2 network. (If you need some extra DOTs, give me a shout with your address, either here on on Riot, I'm jacogr:matrix.parity.io)

Anyway, I've mangled the code to make it show up here https://github.com/polkadot-js/apps/blob/master/packages/app-staking/src/StakeList/Account.tsx#L95

Basically did the following in that function, ugly but shows the issue very clearly -

```
private renderNominee () {
    const { stakingNominating } = this.props;

    if (!stakingNominating) {
      return null;
    }

    const n = (
      <AddressMini
        balance={this.balanceArray(stakingNominating)}
        value={stakingNominating}
        withBalance
      />
    );

    return [n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n];
  }
```

The nominators/nominee gets rendered the same and in the same place, so the above basically just duplicates the normally single nominee to show the same type of output the validators see. IF we get that fixed your see the `renderNominators` will have the same result.

**Comment by jacogr** [comment] 2018-09-21 08:06
I'm guessing maybe we want to do something on the overview page as well -

<img width="528" alt="polkadot apps portal 2018-09-21 10-04-08" src="https://user-images.githubusercontent.com/1424473/45868351-c2b8ef80-bd85-11e8-94ea-50d1bcdd550b.png">

For now, it still looks ok, however if we start getting 100's of nominators, it could become problematic. (Already @chevdor seems quite popular.) We could kick this can down the road a bit as well and just focus on the original issue - just mentioning it here. (The rendering between the 2 is different, so not sharable either)

**Comment by marnibrewster** [comment] 2018-09-23 15:42
Ok - got a local node running and will play around. Will reach out for DOT if needed. Thanks!

**Comment by marnibrewster** [comment] 2018-09-24 00:04
I know @jacogr is busy with API work, but here is screenshot of implementing the hack for renderNominators with requested CSS, and setting isPadded to false for the addressMinis. I am happy to press pause on this until the API work is done, just let me know. 
<img width="1094" alt="screen shot 2018-09-23 at 8 01 37 pm" src="https://user-images.githubusercontent.com/13192976/45934395-b7271d80-bf6b-11e8-86cf-11c506b1e4c8.png">

**Comment by jacogr** [comment] 2018-10-01 15:12
@marnibrewster Sorry, I missed this _completely_ ... I need to pay attention :(

This will not be affected at all nor will it be any work wasted, so please PR. (Really happy to have that in-place.)

**Comment by jacogr** [comment] 2018-10-09 17:52
Linked PR merged.

**Closed by jacogr** 2018-10-09 17:52 UTC
Labels: @app-staking, @ui, enhancement, good first issue
