### ISSUE TITLE
Democracy UI out of sync after cancelling a referendum

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/apps#836] opened 2019-03-24 05:58 UTC
Start a basic `substrate --dev` chain and connect via this UI. Use the Extrinsics tab (or any other method) to create a proposal and usher it along to a  referendum. Once it is in the referendum phase, cancel it (eg. with the sudo module).

Observe that on the Democracy the referendum itself is gone but the "no available referendums" text has not re-appeared. Further, the active count is still at 1.

![image](https://user-images.githubusercontent.com/2915325/54875587-43f64b00-4dd8-11e9-8e7f-5dc3b9cc2ee8.png)

**Comment by jacogr** [comment] 2019-03-24 06:39
Weird one. Cannot reproduce at all with 5 in a row. 

Since the "no available referendums" and "active count" is not derived from each other, but rather separate storage entries. e.g. active is `democracy_referendumCount.sub(democracy_nextTally)` it is not an "ui doesn't refresh when it already has updated info issue".

**Comment by JoshOrndorff** [comment] 2019-03-24 16:23
Wow, thanks for such fast attention to this. Playing with more this morning using `substrate 0.11.0-56332a83-x86_64-linux-gnu` and `polkadot-js/apps 0b36006` it seems that the "no available referendums" text now re-appears as expected. I guess that's what #837 did.

Active count remains off after canceling.

Thanks again, and lmk if I can help test, or pair-program.

**Comment by JoshOrndorff** [comment] 2019-03-24 16:25
I'm not clear what you mean by "Cannot reproduce at all with 5 in a row. (And 6 & 7 in inactive tabs)"

You mean 5 proposals in a row? Active browser tabs running the UI?

**Comment by jacogr** [comment] 2019-03-24 18:14
Yes, indeed. 

The linked PR addresses one of the issues (couldn’t reproduce it, but saw it as a possibility), where the “no active” is not displayed.

**Comment by jacogr** [comment] 2020-01-22 09:46
This should be fixed now after the multi refresh changes on the API.

**Closed by jacogr** 2020-01-22 09:46 UTC
Labels: +P3, @app-democracy, [bug]
