### ISSUE TITLE
Extrinsic changes after switching from "Decode" to "Submission" tab

### ISSUE THREAD

**Issue by AndreiEres** [polkadot-js/apps#8743] opened 2023-01-10 08:22 UTC
On "Decode" tab call data decodes correctly, but after switching to "Submission" tab extrinsic changes. You can see it by the changed call hash. 

Inputs for "locked" and "perBlock" amounts used to be only in planks, but now they use SI. Looks like an input with SI rounds value after moving from "Decode" tab.

<img width="1470" alt="Screenshot 2023-01-10 at 09 11 07" src="https://user-images.githubusercontent.com/27277055/211497086-be7148ee-b9ab-4cd2-a4a8-b2f1fb7cd61f.png">

Link with that call data
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.dwellir.com#/extrinsics/decode/0x130200ec44da6bcd5f7da9c07404b516314e1374f1319d99c4fabb8a5865139d36b93ce8030000000000000000000000000000010000000000000000000000000000008cdcd700

**Comment by jacogr** [comment] 2023-01-10 14:14
Duplicate of https://github.com/polkadot-js/apps/issues/8736

(However this one does have a reproducable testcase, which is good)

**Closed by jacogr** 2023-01-10 14:14 UTC
