### ISSUE TITLE
Query storage at a historical block

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#5738] opened 2021-07-01 10:15 UTC
Very useful to check balances in a old block.

One use case is because XCM emits no transfer events, it is very hard for me to figure out much I received because there is a fee.

If I can just query balances between two blocks, I can see the change. Also useful for other debugging purpose.

**Comment by jacogr** [comment] 2021-07-02 07:12
Duplicate of https://github.com/polkadot-js/apps/issues/3526

**Closed by jacogr** 2021-07-02 07:12 UTC
Labels: <duplicate>
