### ISSUE TITLE
Preimages now use RequestStatusFor

### ISSUE THREAD

**Issue by dnjscksdn98** [polkadot-js/apps#10141] opened 2024-01-04 04:43 UTC
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Due to the major update on `pallet-preimage` ([ref.](https://github.com/paritytech/polkadot-sdk/pull/1363)), it seems that the original storage value `StatusFor` has been deprecated and now `RequestStatusFor` is used instead.
But it seems that the preimage page ([ref.](https://github.com/polkadot-js/apps/blob/9c911354f421fca2c1a6b159bda5934772064656/packages/apps-routing/src/preimages.ts#L14)) are only referencing to the `StatusFor` field.
So for chains that had upgraded their runtime higher than `v1.2.0` (that contains the upper-mentioned PR), will have some incompatibility among preimages. I guess the stored preimage data is fine, but it's just the data display issue on the page.
In my opinion, both `StatusFor` and `RequestStatusFor` should be supported. The reason is because some chains might not yet upgraded their runtime, or either, the lazy storage migration might not have been done.
<img width="1761" alt="스크린샷 2024-01-04 오후 1 42 57" src="https://github.com/polkadot-js/apps/assets/59077132/ec797517-adc3-4fff-a870-bfcd1483b0a3">

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by dnjscksdn98** [comment] 2024-01-10 09:18
Also mentioned on this [issue](https://github.com/paritytech/polkadot-sdk/issues/2869), every action related to preimages won't work such as governance using `pallet-democracy`. The issues that I've encountered was that even though the proposal has been passed, `pallet-scheduler` wasn't able to call the proposal emitting a `CallUnavailable` event.

**Comment by albertov19** [comment] 2024-01-31 12:11
Hey, @dnjscksdn98, I noticed the same issue as new preimages are no longer shown in the "Preimages" tab of governance. I guess this is expected because of what you mentioned above. 

I do see also a bunch of errors in the console

**Comment by andresilva** [comment] 2024-02-19 20:02
cc @TarikGul could you look into this? I just found this issue while submitting a fellowship proposal. Came here to report it but the issue already exists.

**Comment by TarikGul** [comment] 2024-02-26 13:20
@andresilva Thanks for pinging me. I'll have a look into this.

**Comment by TarikGul** [comment] 2024-02-26 21:03
Okay so good news is I was able to reproduce the issue and also semi-fix it. The only problem being giving support for both storage entries is a little tricky (there is quite a lot of abstraction happening with all the hooks and page refs). None the less I will find a solution soon! Thanks for the patience.

**Comment by TarikGul** [comment] 2024-02-29 21:34
Fixed via: https://github.com/polkadot-js/apps/pull/10310

**Closed by TarikGul** 2024-02-29 21:34 UTC
