### ISSUE TITLE
Chainstate adds different property than selected

### ISSUE THREAD

**Issue by yangwao** [polkadot-js/apps#1828] opened 2019-11-01 18:47 UTC
At https://polkadot.js.org/apps/#/chainstate I was trying to add from Storage session validators() and it will add staking offlineSlashGrace. 
I was adding staking offlineSlashGrace in the previous set. I've recorded it https://photos.app.goo.gl/DeJCAJ7xU6sHHg4U6
Keep up good work ✌️😍

**Comment by jacogr** [comment] 2019-11-01 19:50
This is sadly a won't fix. We are dropping support for V1. 

The issue is the dedup key prefix, which is not properly detected (not a V1 feature) - yes, a bug, but not worth wasting time on for a deprecated platform.

**Closed by jacogr** 2019-11-01 19:50 UTC
