### ISSUE TITLE
Assertion failed when estimation amount empty in staking targets

### ISSUE THREAD

**Issue by 0x7CFE** [polkadot-js/apps#2770] opened 2020-05-19 05:36 UTC
tldr:

1. Go to https://polkadot.js.org/apps/#/staking/targets
2. Erase the "amount to use for estimation" field
3. UI crahses with the following message: "Uncaught error. Something went wrong with the query and rendering of this component. Assertion failed"

**Comment by jacogr** [comment] 2020-05-19 07:28
Werid. Doesn't crash for me. Which browser are you using?

**Comment by 0x7CFE** [comment] 2020-05-19 08:57
> Werid. Doesn't crash for me. Which browser are you using?

I was using Firefox 75.0 from Ubuntu 18.04.4 LTS. I was able to reproduce the bug several times then, but right now I could not reproduce it either :man_shrugging:

**Comment by jacogr** [comment] 2020-05-19 09:12
My FF is a bit newer, also couldn't reproduced on it. (dev or deloyed) But where there is smoke, there is fire, so something is indeed weird somewhere - but a nightmare to track without an in-dev crash to see "where".

**Comment by jacogr** [comment] 2020-06-27 11:35
Fixed in #2989

**Closed by jacogr** 2020-06-27 11:35 UTC
Labels: <unconfirmed>, @app-staking
