### ISSUE TITLE
Addresses and Indicies of the same address display different icons

### ISSUE THREAD

**Issue by phillux** [polkadot-js/apps#3284] opened 2020-07-29 10:21 UTC
![both](https://user-images.githubusercontent.com/6450379/88788681-fa6cfb80-d195-11ea-921f-f82ae81237ec.png)
![realgar_address](https://user-images.githubusercontent.com/6450379/88788690-fd67ec00-d195-11ea-8d04-b5559e651c74.png)
![realgar_index](https://user-images.githubusercontent.com/6450379/88788699-0062dc80-d196-11ea-8f5f-eba371835917.png)

The icon displayed for an address changes when using its index. This makes it difficult for a user to verify that they've typed in the index correctly.

**Comment by jacogr** [comment] 2020-07-29 10:27
Duplicate of #3235

**Closed by jacogr** 2020-07-29 10:27 UTC
