### ISSUE TITLE
CANT TRANSFER

### ISSUE THREAD

**Issue by chicco13** [polkadot-js/apps#4196] opened 2020-12-12 04:06 UTC
<img width="1119" alt="Screen Shot 2020-12-12 at 2 01 30 pm" src="https://user-images.githubusercontent.com/33196679/101973361-3d31fa80-3c83-11eb-928f-47c260853cce.png">
this  keeps coming up

**Comment by jacogr** [comment] 2020-12-12 08:59
I can replicate this using Enzyme on a local network. The signing on Enzyme fails, honestly have no insight into the working there. It could be (and this is a wild guess), that the network is not as expected, i.e. it show Kusama/Edgeware for me, no other networks.

I would suggest asking Enzyme as to what may b the cause, in this case there is nothing the apps UI itself can do to make tis succeed.

**Comment by jacogr** [comment] 2020-12-19 13:11
Closing. Logged on Enzyme.

**Closed by jacogr** 2020-12-19 13:11 UTC
Labels: <support>
