### ISSUE TITLE
.css -> .scss?

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#803] opened 2019-03-11 02:16 UTC
Currently CSS files are all .css. 

With SASS currently being used lightly in the project, it's probably worth moving to .scss now. IDEs I've tested, Atom and Sublime, are becoming confused with formatting syntax because of the .css suffix.

**Comment by jacogr** [comment] 2019-03-11 06:57
The idea is to move all to styled-components so 2 approaches - only rename css files when touched or (when touched) just do the conversion to styled-components as intended. Been following the second part myself (with some exceptions). 

Would not go for an Big Bang rename here when it has a limited lifetime.

**Comment by jacogr** [comment] 2019-03-29 21:46
Closing this, I think we are on the same page judging by the current work.

**Closed by jacogr** 2019-03-29 21:46 UTC
Labels: @apps, question
