### ISSUE TITLE
Batch Basket

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3973] opened 2020-11-05 10:31 UTC
Add the option to "add to basket" any extrinsic submission. I.e. on the tips screen, I can add the closing of 4 different tips to a basket. Then I'll stop by Account and basket up two transfers. Then I'll stop by Democracy and add my referendum vote to my basket.

Clicking the "basket" or "shopping cart" icon takes the user to a new UI where the pending extrinsics are grouped by account. The groups can then be issued using `batch` or `batch_all`.

If this sounds interesting, we can make it a bounty or an RFP. I'd be happy to write it up.

**Comment by jacogr** [comment] 2020-11-05 11:27
Duplicate of https://github.com/polkadot-js/apps/issues/3339

**Closed by jacogr** 2020-11-05 11:27 UTC
