### ISSUE TITLE
If a stash is its own controller, it should still be able to unbond

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#1118] opened 2019-05-09 18:56 UTC
Here is an example of a mistake I made that I cannot recover from.

I bonded Charlie with itself as controller and session:
![image](https://user-images.githubusercontent.com/738724/57478986-a8903b00-729c-11e9-8e25-93e35c37a1c4.png)

In general, if you want an account to no longer be a stash, this is no problem as seen below:
![image](https://user-images.githubusercontent.com/738724/57479021-be056500-729c-11e9-8413-cd935f6ee41b.png)

But in the case of Charlie, it can only validate and nominate:
![image](https://user-images.githubusercontent.com/738724/57479042-ceb5db00-729c-11e9-875e-29aae0dbd935.png)

It should additionnally be able to unbond and increasing bonding:
![image](https://user-images.githubusercontent.com/738724/57479062-dd9c8d80-729c-11e9-876a-44a23f785fca.png)

or we need to prevent even getting into this situation by not allowing a stash to be its own controller.

**Comment by jacogr** [comment] 2019-05-09 19:59
Duplicate of #1074

**Closed by jacogr** 2019-05-09 19:59 UTC
