### ISSUE TITLE
Decode democracy preimages

### ISSUE THREAD

**Issue by dzmitry-lahoda** [polkadot-js/apps#8246] opened 2022-10-18 14:41 UTC
I'm submitting a feature request to allow decode democracy preimages easily.

Currently if I want to create preimage I have to type all message manually.

It is very slow and error prone for big batched XCM messages.

Would be awesome that I can decode preimage creation same way I do usual extrinsics operations.

Currently click our window of preimage creation or transaction failure looses all my typing and I have to start again.

Similar to https://github.com/polkadot-js/apps/issues/8245

**Comment by jacogr** [comment] 2022-10-18 16:21
Duplicate of https://github.com/polkadot-js/apps/issues/8245 - all `Call` elements are exactly the same, this is generic.

**Closed by jacogr** 2022-10-18 16:21 UTC
