### ISSUE TITLE
Option<Option<_>> rendering bug

### ISSUE THREAD

**Issue by MucTepDayH16** [polkadot-js/apps#7010] opened 2022-02-21 12:51 UTC
Using nested `Option<_>` leads to unavailability of choosing inner option

<img width="1354" alt="Screenshot 2022-02-21 at 14 22 18" src="https://user-images.githubusercontent.com/29900537/154957531-0464ee0b-baf2-474a-8cac-297d585cf5e6.png"><img width="1354" alt="Screenshot 2022-02-21 at 14 22 25" src="https://user-images.githubusercontent.com/29900537/154957546-9bf609e1-7222-4a9c-9287-46ab506a39e8.png">

**Comment by jacogr** [comment] 2022-02-21 13:28
Duplicate of https://github.com/polkadot-js/apps/issues/2233

**Closed by jacogr** 2022-02-21 13:28 UTC
Labels: <duplicate>
