### ISSUE TITLE
No governance forum icons and option to see status of account vote

### ISSUE THREAD

**Issue by oshakarishvili** [polkadot-js/apps#8384] opened 2022-11-21 16:27 UTC
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behaviour and expected behaviour?**
  - Currently, it is not possible to see if an account has voted on the referendum and what their decision was. 
  - Additionally, we lack governance forum icons on the left side of the referenda to be able to easily retrieve the contextual info. 
   

Thanks!

**Comment by jacogr** [comment] 2022-11-21 17:14
The first one is a duplicate of https://github.com/polkadot-js/apps/issues/8341

The second is not a bug, it is up to the providers to add their links (Subsquare has done so a short while ago)

**Closed** 2022-11-29 19:45 UTC
Labels: <duplicate>
