### ISSUE TITLE
Warning Modal to Backup Seed Phrase Should Have The Seed Phrase in it

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/apps#394] opened 2018-11-02 20:34 UTC
![screen shot 2018-11-02 at 1 30 31 pm](https://user-images.githubusercontent.com/10432070/47939138-822fb400-dea3-11e8-8a93-65512935fdbf.png)

Just need to add the seed phrase component from create screen and hover to copy.

**Comment by jacogr** [comment] 2018-11-09 10:00
Additionally allow the download of the account here - potentially even force the issue, show download button, don't proceed (don't allow dialog to be closed) until user has actually downloaded the file.

**Comment by Stefie** [comment] 2018-11-12 10:20
Hi, I'd like have a look at this one.
I noticed that `master` hasn't been updated for a while and most pull requests are on `next`.  Should I branch off from `next`, too?

**Comment by jacogr** [comment] 2018-11-12 11:15
@Stefie Yes, next would be better.

The issue is as follow - for PoC-2 (master) it mirrors what is on the current network. However PoC-3 is quite close and a lot of stuff underlying has changed - the APIs are not compatible at all. (So we are about 2-3 weeks out from having next become master).

**Comment by jacogr** [comment] 2018-11-12 13:08
Yes, sorry about that - wrapping up PoC-3 has taken a bit longer than anticipated, so a "we will only have this branch for a week or two" became, well, a month or two :) With PoC-1 to P-C-2 we could support both in a single branch, here it was really impossible to do since we needed to completely replace the API layer.

I'm guessing we should have done a better job of highlighting this in the README at least.

**Comment by Stefie** [comment] 2018-11-12 16:16
@jacogr No worries at all! In this case you probably had more important things to do than updating the docs. Master was still running smoothly. :)
But that also means, that I need to install polkadot from the polkadot.git and that v0.2 from the substrate.git repository is not working with the `next` branch, right? Is there a way to run a local development network on PoC-3 like `polkadot --dev` on PoC-2? 
Or shall I just go with BBQ Birch for the time being?

**Comment by jacogr** [comment] 2018-11-12 16:56
Yes. Indeed.

So the same process as polkadot, just get latest substrate, do the `./scripts/build.sh` & `cargo build --release` dance and run it with `substrate --dev` (I normally just combine the last 2 steps with `cargo run --release -- --dev`

**Comment by jacogr** [comment] 2018-11-12 16:57
^^^ There may be a DB mismatch, you can purse the chain via `cargo run --release -- purge-chain --dev`

**Comment by Stefie** [comment] 2018-11-13 14:57
#447

**Comment by jacogr** [comment] 2018-11-14 10:00
Closed in #447 (next branch)

**Closed by jacogr** 2018-11-14 10:00 UTC
Labels: @app-accounts, enhancement, good first issue
