### ISSUE TITLE
Transfer to indices index(SS58), decoding mistake

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#3520] opened 2020-08-26 02:59 UTC
Transfer to indicators index(SS58), decoding mistake, will transfer to another address.

**Comment by jiangfuyao** [comment] 2020-08-26 03:02
https://polkascan.io/polkadot/transaction/0x70fab89d1338942029841cc5d775068c478d39de84e2bb2928e02d22fd59f8ef

**Comment by jiangfuyao** [comment] 2020-08-26 03:02
https://polkadot.subscan.io/extrinsic/1311788-4

**Comment by xlc** [comment] 2020-08-26 03:06
Trying to transfer to 12RdYp, but polkadot somehow misinterpret what I want to do

<img width="717" alt="Screen Shot 2020-08-26 at 3 04 54 PM" src="https://user-images.githubusercontent.com/1201310/91250585-81b98900-e7ad-11ea-90bf-dc35f06af820.png">
<img width="740" alt="Screen Shot 2020-08-26 at 3 05 05 PM" src="https://user-images.githubusercontent.com/1201310/91250594-87af6a00-e7ad-11ea-8ad6-33115c4bd6bb.png">

**Comment by xlc** [comment] 2020-08-26 03:14
decode 16ZZ5T1yChDbXHRzHW274ryqaeaeaQuUpNuBzMf9ucqPmA9R give me 
0xf601000000000000000000000000000000000000000000000000000000000000

and 0x01f6 is 502, which is 12RdYp decoded to

I guess we can't have the 1DOT back.

**Comment by jacogr** [comment] 2020-08-26 05:10
On Polkadot/Kusama The following is configured https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/polkadot.ts#L10

This means that, unlike chains with indices lookups, there is no distinction not space savings.

**Comment by xlc** [comment] 2020-08-26 05:26
I see. But it is still a bug that it convert the index into unexpected address.

**Comment by jacogr** [comment] 2020-08-26 05:36
Indices are valid on chains that do support IndicesLookups as a destination. There is no reverse lookup to replace indices with AccountIds in sending since it removes space-saving on the non-IdentityLookup chains. 

Yes, the balance lookup and identity icon does that since it has to map to AccountId for operation.

**Comment by xlc** [comment] 2020-08-26 05:52
The issue is it is not valid for Polkadot but not disabled and it definitely looks like will work when user enter an account index.
The easy way just to make sure `api.createType('AccountId', api.createType('AccountIndex', '12RdYp'))` will throw an error instead of creating address without private key.

**Comment by jacogr** [comment] 2020-08-26 06:02
The only people who are aware of AccountIndexes are advanced users since the UI has no support for registering it, does not use it as-available for spece savings (it used to) it even goes so far on not storing them when added via contacts. So where users are using AccountIndex, they should be aware of the on-chain specifics, i.e. in Polkadot/Kusama it is more akin to a vanity identifier since it is never used in transactions.

There could be an additional check added to the API when creating an AccountId with non-32-bytes, feel free to log an issue there for an extra assertion, it could add value to the ecosystem.

**Comment by jacogr** [comment] 2020-08-26 06:10
On the back of https://github.com/polkadot-js/apps/issues/3499 an attempt was made to use something in the wrong way without understand the chain config. Closing since the UI doesn't actually encourage nor provide the tools for these.

**Closed by jacogr** 2020-08-26 06:10 UTC
Labels: <question>
