### ISSUE TITLE
EthTransaction type error on production

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#4335] opened 2021-01-07 15:26 UTC
When trying to look at extrinsics on testnet from https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.testnet.moonbeam.network#/explorer/node reports multiple errors in the console. Ex:

REGISTRY: Error: createType(Call):: Call: failed decoding ethereum.transact:: Struct: failed on args: {"transaction":"EthTransaction"}:: Bytes length 13516226 exceeds 10485760

When trying to reproduce this error with the latest version of apps locally, the errors didnt show.

Maybe the latest version hasn't been deployed?

**Comment by jacogr** [comment] 2021-01-07 15:29
The apps UI is on API 3.3.2 (there has not been pushes to master after that, so it matches 100% with the API)

**Comment by jacogr** [comment] 2021-01-07 15:30
When that fails, it probably means the field before that failed - i.e. it may be the field before it.

**Comment by joelamouche** [comment] 2021-01-07 15:59
there is this error also:
![Screenshot 2021-01-07 at 16 59 18](https://user-images.githubusercontent.com/16758383/103914176-b9e0b900-5109-11eb-82a6-bfd0348da4ae.png)

How do you explain the error doesn't display on a local running apps instance?

**Comment by jacogr** [comment] 2021-01-07 16:09
peers() is an unsafe RPC, it is not exposed on remote nodes.

**Comment by jacogr** [comment] 2021-01-07 16:39
Do you have a blockHash for a failure to look at?

**Comment by jacogr** [comment] 2021-01-07 16:44
Ahhh... hang tight. It is pendingExtrinsics.

Josh complained about that as well in Substrate Tech.

The transaction there is in the pool, but the JS API cannot decode it and neither can the node. (The nodes fail to process it). so basically it is something invalid that will hang around forever and can never be executed since nothing can understand what it is.

**Comment by crystalin** [comment] 2021-01-07 16:52
@jacogr I think it happens on valid Extrinsics too, see:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.testnet.moonbeam.network#/explorer/query/0xccb954325225912e0322dd8d6e179b460975e2c10c5d32a14dcae18aacec879b

**Comment by jacogr** [comment] 2021-01-07 16:57
Ok, the second is real specific issue then (the pending nothing that can be done about).

**Comment by joelamouche** [comment] 2021-01-07 17:36
Was able to make a test isolating the api call:
```
import { ApiPromise, WsProvider } from "@polkadot/api";
import { typesBundle } from "moonbeam-types-bundle";
async function main() {
  const wsProvider = new WsProvider(`ws://localhost:30544`);
  const polkadotApi = await ApiPromise.create({
    provider: wsProvider,
    typesBundle,
  });
  const signedBlock = await polkadotApi.rpc.chain.getBlock();
  console.log("signedBlock", signedBlock.block.header.number.toString());
}
main();
```

Interestingly, it throws the same error when connected to testnet, but not when connected to local moonbeam

**Comment by jacogr** [comment] 2021-01-07 17:49
The issue is the following - the Transaction maps to the transaction in frontier, but the actual one used in transact is this - https://github.com/rust-blockchain/ethereum/blob/master/src/transaction.rs#L222 (No idea how that is encoded when used in frontier atm)

**Comment by jacogr** [comment] 2021-01-07 17:50
And it will be intermittent - depending on what is in the message, so it may decode as bullshit when when not failing.

**Comment by joelamouche** [comment] 2021-01-07 17:58
🤔 But hasn't it been the case for a long time?

**Closed** 2021-01-07 19:06 UTC
