### ISSUE TITLE
Brace for the new reward logic in nomination pools

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#7741] opened 2022-06-15 18:41 UTC
As described in https://github.com/paritytech/substrate/pull/11669, the logic for how the rewards are computed is changing in a non-compatible way. This needs some catering for, until all chains are updated with the new logic.

**Comment by kianenigma** [comment] 2022-07-25 16:00
This is about to be baked into the 9.26 release pretty soon FYI https://polkadiff.parity.io/

**Comment by jacogr** [comment] 2022-07-25 16:52
Thank you. May have to disable it as detected until support is in.

**Comment by kianenigma** [comment] 2022-07-25 20:43
FYI, even though you said it won't be handy, I am adding this: https://github.com/paritytech/substrate/pull/11831

The transaction to claim rewards is exactly the same as  before. We could also add a endpoint that returns the pool's total pending reward.

You can re-implement the logic on your side, but RPC sounds much more sustainable to me.

**Comment by kianenigma** [comment] 2022-07-25 20:43
This will probably make it to 9.27

**Comment by kianenigma** [comment] 2022-07-25 20:47
If you say this will help you, I will see if we can add the RPC in 9.26 as well.

**Comment by kianenigma** [comment] 2022-08-17 18:04
A ping on this, as this will be soon enabled on Kusama and not all functions work (see Westend.).

Pools will also be on Polkadot hopefully in the next 4-8 weeks, which makes https://github.com/polkadot-js/apps/issues/7808 and https://github.com/polkadot-js/apps/issues/7902 pretty important too.

**Comment by kianenigma** [comment] 2022-09-01 11:53
fwiw, here's an example of how to compute the pending rewards in JS (using overflow prone vanilla number type): 

https://github.com/substrate-portfolio/polkadot-portfolio/pull/16/commits/2994166ccb2bd3c0674e6cd3f0e4bb419217a8e4

Once https://github.com/paritytech/substrate/pull/12095 is merged (9.29), you can use this RPC.

**Comment by jacogr** [comment] 2022-09-04 10:08
The UI currently does retrieve rewards using the runtime call, but as suggested above, it is not quite working on Westend for me at least (everything is always 0 at this point, even with unclaimed pool rewards).

**Comment by kianenigma** [comment] 2022-09-06 07:01
If you want to support it now (which I encourage you do), you should use something along the lines of the link above: https://github.com/substrate-portfolio/polkadot-portfolio/pull/16/files#diff-17782fa0982182d57be83b90b00797e4ef1da85220c6780e23e310f272389aecR225

Once 9.29 is enacted, we will have the runtime API working again.

**Comment by jacogr** [comment] 2022-09-06 12:10
Thanks for confirming. my observations 

I will close this then since the UI does support the correct logic to cater with rewards. Obviously because of an oversight this is not quite working as of yet (it happens) however it seems the runtime call bug has been addressed - once that is in, the UI will "just work, no adjustments" since the runtime is now properly treated as "the source of truth".

PS: Putting in code to work around bugs and then removing it is not quite maintainable with multiple runtimes. And even with the link, I do have my own implementation that was reverse-engineered, however maintenance-wise this is a dead-end and it it not going in. I would just suggest getting the fixed into the networks as a priority, starting with Westend. 

(Other codebases may obviously have differing opinions on this and be willing to pay the long-term maintenance price of "either this or that since we cannot trust the runtime", I just believe the cause needed to be fixed instead of plastered over.)

Thanks for the pointers and especially the runtime interfaces which is "the right way to go(tm)", this would be great when fully enabled and runtime, no-bug functional on all relay chains.

**Closed by jacogr** 2022-09-06 12:10 UTC
Labels: @app-staking, -size-m
