### ISSUE TITLE
Open Google Translate, the pages will break

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#2154] opened 2020-01-20 11:21 UTC
This problem occurs when I use Google Chrome and open Google Translate and open the https://polkadot.js.org/apps/#/society. (and other some pages)

![屏幕快照 2020-01-20 下午5 24 44](https://user-images.githubusercontent.com/34789555/72722747-0ad66500-3bba-11ea-8615-1ebc32d86cdc.png)

Tested close the Google Translate, not have issue.

**Comment by jacogr** [comment] 2020-01-20 12:48
This one seems quite problematic and is caused by having translation on the app via react-i18next. It seems to want to remove the node based n string, but since it has been changed by an extension, cannot do so.

The correct approach here (specifically for this single case), would really be to make sure we get the cn translation 100%, so we don't have the need for any extra tools. Society is new, so it has no translated text at all.

Sadly, not even sure how to else address this issue for a 3rd-part (important) lib.

**Comment by jacogr** [comment] 2020-01-20 13:46
@jiangfuyao Can you check the society page against the current version of the https://polkadot.js.org/apps/ - in that case am doing things _slight_ differently (only place), if that does have an impact there is something that can be done code-wise.

**Comment by jacogr** [comment] 2020-11-28 15:35
Closing. Nothing that we can explicitly do code-wise, apart from making sure the translations are quite comprehensive.

**Closed by jacogr** 2020-11-28 15:35 UTC
Labels: -size-m, @apps, [bug]
