### ISSUE TITLE
Encountered a problem in firefox

### ISSUE THREAD

**Issue by Prevo89** [polkadot-js/apps#2723] opened 2020-05-12 13:18 UTC
I encountered a problem in firefox during the voting process.
As you can see in the attachment, as soon as I try to scroll down the list of candidates, the visual bug appears and doesn't allow to select anything anymore.
![Screenshot_2](https://user-images.githubusercontent.com/52075554/81696040-b6563e80-9463-11ea-9a9f-bb5f21128f86.jpg)

**Comment by jacogr** [comment] 2020-05-12 14:29
Will have to take a look, but exceptionally weird. Wonder if this is the only one that show that or if is is caused by the selector (which means it could show in nominations as well)

**Comment by jacogr** [comment] 2020-05-13 09:09
What version of FF? I tested on 75.0 and then updated to 76.0.1 and I cannot replicate, so cannot figure out where it goes wrong :( Scrolled quite a bit inside the lists.

**Comment by jacogr** [comment] 2020-05-28 13:03
Closing. Feel free to re-open if this is still an issue, with the specific version & OS so it can actually be reproduced. On latest FF, this does not happen for me (although it def did happen above).

![image](https://user-images.githubusercontent.com/1424473/83145012-6f6b7880-a0f4-11ea-9e74-d2e63e0d1b14.png)

**Closed by jacogr** 2020-05-28 13:03 UTC
Labels: +P3, -size-s, @app-council, [bug]
