### ISSUE TITLE
Add bonding-specific checks (incl. freeBalance vs transferrable)

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#1823] opened 2019-11-01 12:38 UTC
I have received reports that 
1- someone has told me that they cannot stake their vested tokens. It looks like the max amount that the UI allows is what it shows to you as _available balance_. 
  - What is the formula to calculate this? it looks like it is either wrong, or should not have been used for staking.
2- I asked them to submit the transaction manually and now they cannot see any balance in their account page. Looks like whatever code was calculating the available balance (the rest are raw values so I assume they are safe.) crashed. 

All in all, it should be clear that people can use vested tokens for staking. cc @Tbaut

**Comment by jacogr** [comment] 2019-11-01 13:15
The calculation is not "wrong" - the issue is that the UI looks at transferrable (aka all available) instead of freeBalance (which is the actual possible bonded amount). There are no specific overrides for bonding checks as of yet.

**Comment by jacogr** [comment] 2019-11-01 13:16
For the second part (which is a different issue/bug), I would appreciate the problematic address to check against the addresses page. (i.e. same view is used inside). Without a reproduction, it is "slightly" difficult to track.

**Closed** 2019-11-01 14:19 UTC
Labels: +P3, @app-staking, @ui-signer, [enhancement]
