### ISSUE TITLE
UI can show wrong info meanwhile the voting process is running.

### ISSUE THREAD

**Issue by iammelea** [polkadot-js/apps#1352] opened 2019-06-27 16:02 UTC
For reproducing this:
1.- Vote yay stash account
2.- vote yay controller account

Here I can see the info ok in the UI
BUT if

3. vote yay stash account x 2 times the info change after vote
![Screenshot from 2019-06-27 16-42-07](https://user-images.githubusercontent.com/38863192/60281564-6a5ee180-9905-11e9-8e71-2ae80654c88e.png)

now at this point, the UI shows the info erroneously, the opposite

but at the end shows like is ok the vote was yay, not nay the winner. 

![Screenshot from 2019-06-27 16-43-24](https://user-images.githubusercontent.com/38863192/60281627-89f60a00-9905-11e9-85b6-d52b090fc5f3.png)

**Comment by yjkimjunior** [comment] 2019-06-27 16:07
related: https://github.com/polkadot-js/api/issues/1034

**Comment by Tbaut** [comment] 2019-06-27 16:12
Not sure if it's related to it, the screenshot shows that yay has more vote, unlike the diagram.
I guess it's been introduced by https://github.com/polkadot-js/apps/pull/1317

I could reproduce with 2 votes with the same amount of dots, and the diagram is wrong, not the voting.
![image](https://user-images.githubusercontent.com/33178835/60282390-25d44580-9907-11e9-9476-64f608493bd4.png)

**Comment by iammelea** [comment] 2019-06-29 19:55
Ty 
https://github.com/polkadot-js/apps/pull/1353

**Comment by Tbaut** [comment] 2019-06-29 19:58
Thanks, I reopened as the issue will be closed automatically when the PR is merged.

**Closed** 2019-06-30 08:42 UTC
Labels: @app-democracy, [bug]

**Comment by Tbaut** [comment] 2019-06-30 08:45
We should pay extra attention in the future as the PR that got merged fixes a display problem but I couldn't reproduce what is discribed here e. g: vote show a vast majority of nay, but the referendum passes.

**Comment by iammelea** [comment] 2019-06-30 10:29
Still there. Just used Chorme and I can see the same. After vote the display show wrong info. But if F5 then the info is correct.
