### ISSUE TITLE
Null parameter display as 0 on Event

### ISSUE THREAD

**Issue by leonardocustodio** [polkadot-js/apps#7411] opened 2022-04-20 20:24 UTC
On polkadot.js when we display at events a null parameter (that is optional). It shows as 0.
Because of that, it is impossible for the person to know if the parameter was indeed 0 or null.

![image](https://user-images.githubusercontent.com/5619696/164316487-7522ab1f-38ba-43c4-af70-f8d10eb79a0e.png)
![image](https://user-images.githubusercontent.com/5619696/164316422-b2409557-15a5-48cd-9c4b-29d282b0d31c.png)

**Comment by jacogr** [comment] 2022-04-21 04:48
Seems like an issue with the `Option<number>` Component. Do you have a a link to the chain and blockhash for me as a testcase to check on?

**Comment by leonardocustodio** [comment] 2022-04-21 14:23
Here is the chain and one block that I've just made the transaction: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.rococo.efinity.io#/explorer/query/0x1bcea28f9c54322cf578de7dac28c7084463d14b8f03da47806e148507ef2b2d

But that's not an archive node. The info about the block will disappear real quickly. But it should be able to reproduce in any chains, I believe.

**Comment by jacogr** [comment] 2023-03-14 16:37
Closing this one for now.

If an issue and actual reproduction would be appreciated alongside logging it. (The above chain doesn't currently exist, so difficult to verify - however since we have reworked `Option` display in `react-params` quite some time back, the underlying issue is now either gone or if something was missed, manifests differently)

**Closed by jacogr** 2023-03-14 16:37 UTC
Labels: needs investigation
