### ISSUE TITLE
Support for ERC-721 string on explorer

### ISSUE THREAD

**Issue by Robbepop** [polkadot-js/apps#3909] opened 2020-10-21 15:10 UTC
Copy of: https://github.com/paritytech/ink/issues/526

> After building erc721, I am testing after deploying the explorer below. I am trying to test by putting some string information in the corresponding id of erc721 through self-customization to support string writing, but it seems that I can't actually write using strings in explorer. (It seems to be only bytes.) Is there a way?
>
> https://polkadot.js.org/apps/#/

**Comment by jacogr** [comment] 2020-10-21 15:36
As commented, need and ABI. It is possible that this is a duplicate issue (and already closed).

**Comment by jacogr** [comment] 2020-10-21 16:15
Re-looking closing outright until proper info is provided. (No sense in making it stick around since it quite possibly is a duplicate of https://github.com/polkadot-js/apps/issues/3886 which is closed now)

As mentioned - issues without proper info is generally closed outright, here it def. lacks complete info and is not actionable. Contracts should -

- have s clear description of any changes made
- supply the ABI (if changes made)

As it stands, it is up in the air with guessing. Feel free to re-open if an issue and and actual testcase is available.

**Closed by jacogr** 2020-10-21 16:15 UTC
Labels: <support>
