### ISSUE TITLE
Make the "Riot" entry on identity set up a more generic one, including Discord or Telegram handle

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#7609] opened 2022-05-19 07:07 UTC
At the moment, on-chain identity setup on Apps only allows you to add your Riot (Element) handle in the specific entry:

<img width="567" alt="Screenshot 2022-05-19 at 09 05 39" src="https://user-images.githubusercontent.com/22815262/169231255-2ac7999a-4fb0-41c9-9076-49fa00af03e3.png">

Many community members don't use Element but other bridged messaging apps like Discord or Telegram: is it possible to include these formats in the entry for the user to choose the best way to contact them?

**Comment by jacogr** [comment] 2022-05-19 07:14
It actually just maps the field exposed by Substrate with the intent there - https://github.com/paritytech/substrate/blob/2b1326a4da39c6a46f6c0e72d07bee38e31a5421/frame/identity/src/types.rs#L240

**Comment by jacogr** [comment] 2023-03-14 16:33
Closing this one. 

There has been a PR merged in the last day or two (see https://github.com/polkadot-js/apps/pull/8381) that adds Discord handles - it allows adding/editing, there is no display for it, but hopefully the developer will PR that soon.

The approach taken was to use the additional fields as intended, i.e. adding an additional `Discord`-named field. (For anything else the same approach can be taken)

**Closed by jacogr** 2023-03-14 16:33 UTC
Labels: needs investigation
