### ISSUE TITLE
Fields with Option<Option<ENUM>> are broken

### ISSUE THREAD

**Issue by leonardocustodio** [polkadot-js/apps#8159] opened 2022-09-22 17:42 UTC
Hello,

When we have a field that is an Option of an Option of an Enum. The polkadot-js UI breaks. And it is not possible to select the enum that we want.

![image](https://user-images.githubusercontent.com/5619696/191815087-abe8263c-de43-4ae9-b7d3-da8a92356567.png)

* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **Please tell us about your environment:**
  - Version: 0.121.2-67-x
  - Environment: 
    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by jacogr** [comment] 2022-09-22 18:15
Duplicate of https://github.com/polkadot-js/apps/issues/2233

**Comment by jacogr** [comment] 2022-09-24 11:24
Closing as duplicate of existing. PRs to address the specific layout issues in play here are always welcome.

**Closed by jacogr** 2022-09-24 11:24 UTC
Labels: <duplicate>
