### ISSUE TITLE
Maximum call stack exceeded when reading tips

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3597] opened 2020-09-02 20:54 UTC
![image](https://user-images.githubusercontent.com/1430603/92035388-eefd8900-ed6e-11ea-97ae-2c68290c0ba2.png)

Kusama. Problem not present on Polkadot.

Updated metadata.
Versions:

- Parity Polkadot v0.8.23-e2ebf25b
- api v1.32.0-beta.8
- apps v0.57.0-beta.7
- Browser: Brave Version 1.14.70 Chromium: 85.0.4183.83 (Official Build) beta (64-bit)

**Comment by jacogr** [comment] 2020-09-03 05:06
Sadly cannot reproduce. Check if you added any custom types.

Additionally, you council account - is it a proxy, multisig, i.e. something non-normal account? (Could be the issue specifically for you)

**Comment by jacogr** [comment] 2020-09-06 08:05
Closing, no further info provided.

**Closed by jacogr** 2020-09-06 08:05 UTC
Labels: <support>
