### ISSUE TITLE
HMR not quite 100%

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#793] opened 2019-03-07 11:28 UTC
<img width="645" alt="polkadot substrate portal 2019-03-07 12-26-19" src="https://user-images.githubusercontent.com/1424473/53953698-4cf6d500-40d4-11e9-8b02-d89060f88bfc.png">

Additionally on changes, it detects, does something (loads the changes) and you end up with a blank page. (Got this by editing the staking app). So we are in a slightly worse position since we now need to reload after the auto load.

**Comment by Stefie** [comment] 2019-03-07 11:35
> on changes, it detects, does something (loads the changes) and you end up with a blank page.

hmm... I can't reproduce that. It's working fine on my machine with Alexander. Did you make a fresh install of the node_modules?

**Comment by Stefie** [comment] 2019-03-07 11:41
(I"m also getting the console.warning, though)

**Comment by jacogr** [comment] 2019-03-07 11:45
It works intermittently... so the last couple it has been working. No idea how to reproduce atm. :(

**Comment by rossbulat** [comment] 2019-03-07 12:25
I also got the hot loader patch warning. It is being discussed [here](https://github.com/gatsbyjs/gatsby/issues/11934) too, not yet resolved.

**Comment by Stefie** [comment] 2019-03-07 13:24
I'm getting slightly annoyed by this warning... tried all suggested solutions to get rid of it but none of them worked. https://github.com/gaearon/react-hot-loader#react--dom

**Comment by jacogr** [comment] 2019-03-07 15:07
Annoying as it is, it is ok - as long as the rest of the stuff is stable...

**Comment by Stefie** [comment] 2019-03-07 15:11
Yeah... so I‘d close this issue for now if none of you two had any issues with HMR tody anymore. I‘ve been working with it today and didn‘t experience any flaws

**Closed** 2019-03-07 17:43 UTC
Labels: @apps, bug, help wanted
