### ISSUE TITLE
Contraact interactions not working

### ISSUE THREAD

**Issue by niklabh** [polkadot-js/apps#8506] opened 2022-12-09 04:04 UTC
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Contract interaction via UI is giving error: { Err: { Module: { index: 70 error: 0x02000000 } } }

![Screenshot from 2022-12-09 04-26-41](https://user-images.githubusercontent.com/874046/206621429-f75eb8b2-1b41-46f5-af0b-d3c7fe85fabd.png)

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

Testing on deployed polkadot.js

**Comment by jacogr** [comment] 2022-12-09 05:38
Duplicate of https://github.com/polkadot-js/apps/issues/8364 (also has a same issue logged recently in https://github.com/polkadot-js/apps/issues/8500)

**Closed** 2022-12-09 05:38 UTC
Labels: <duplicate>
