### ISSUE TITLE
Support custom rpc types in apps-config

### ISSUE THREAD

**Issue by maxsam4** [polkadot-js/apps#2772] opened 2020-05-19 09:04 UTC
This is a feature request to add support for custom rpc type definitions in apps-config for external chains.

**Comment by jacogr** [comment] 2020-05-19 09:10
Duplicate of #2162 

As always, PRs welcome this has been hanging for quite some time and will probably only get priority when things are a bit quieter on support for ongoing chain-support changes.

**Closed by jacogr** 2020-05-19 09:10 UTC
Labels: <duplicate>
