### ISSUE TITLE
1010: Invalid Transaction: Transaction has a bad signature 

### ISSUE THREAD

**Issue by zhp1254** [polkadot-js/apps#3533] opened 2020-08-27 03:36 UTC
RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature 

signed transaction

0x3502844a0fa92a258454f14e2b71c2a624164d3a104695ee4c4bbf52aa7529d3cf3a5901ae2bb2fbbbec40d58aa875258331e3b7722829941bee3640c9dea42be3eafc20935235a201f138e9e4295b5973cec04ba25258f2620685f2aa17c29392706d850000000500cada3945b12638f84db2855fd27d41efef320c574b9a36b77f6b82437a91561f070064dd440b

from account
![image](https://user-images.githubusercontent.com/18046237/91380965-d0702d00-e858-11ea-93a1-406b82bc6c46.png)

to account
![image](https://user-images.githubusercontent.com/18046237/91380980-dbc35880-e858-11ea-822f-23f21aff2c28.png)

send transaction
![image](https://user-images.githubusercontent.com/18046237/91381041-fdbcdb00-e858-11ea-92a9-0cdbc35286df.png)

error
![image](https://user-images.githubusercontent.com/18046237/91381091-16c58c00-e859-11ea-94ce-3476e346e65e.png)

**Comment by jacogr** [comment] 2020-08-27 06:42
No idea what can cause this. Which account type (sr25519/ed25519/edcsa) is the sending account?

**Comment by zhp1254** [comment] 2020-08-27 13:08
> No idea what can cause this. Which account type (sr25519/ed25519/edcsa) is the sending account?

sr25519

**Comment by jacogr** [comment] 2020-08-27 16:36
On all accounts of a specific account? On all txs?

**Comment by zhp1254** [comment] 2020-09-02 01:50
> On all accounts of a specific account? On all txs?

12g7CMKtepkZuE7xDvstNLz2Xf2ZYR7KrZ6VCrVoFqiAT1Vi  just this account occur an error

**Comment by jacogr** [comment] 2020-09-06 08:20
Ok, so when I look at the tx provided here, it would seems nonce & tip is empty (as expected, first transaction), but also the era is empty. The apps UI does create nor submit immortal transactions, so that is exceptionally weird, there should always be an era specified. 

(It explains why it gets invalid tx since the blockHash for the era would be used in the signing, but the era is shown as immortal, while mortal is the default)

Why you would get this when creating a tx via the apps UI is not understandable.

**Comment by jacogr** [comment] 2020-09-18 11:57
Some follow-up questions -

- How did you log the full tx, since it is actually not logged anywhere in the UI
- Still uncertain about the immortal nature of this transaction (which the apps UI does not use), was it generated from the transfer UI?

**Comment by jacogr** [comment] 2020-09-26 18:04
Closing. Feel free to re-open with reproducible steps.  As of now, nothing that can be actioned.

**Closed by jacogr** 2020-09-26 18:04 UTC
Labels: <support>

**Comment by zhp1254** [comment] 2020-09-27 12:03
> Some follow-up questions -
> 
> * How did you log the full tx, since it is actually not logged anywhere in the UI
> * Still uncertain about the immortal nature of this transaction (which the apps UI does not use), was it generated from the transfer UI?

chrome pressF12 ,select Console view
