### ISSUE TITLE
BUG: value overflow

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#258] opened 2018-08-24 01:38 UTC
https://poc-2.polkadot.io/#/extrinsics
staking -> transfer
inupt :   valude:Balance   10000000000000....  overflow, page dead.

**Comment by jacogr** [comment] 2018-08-24 08:55
Duplicate of https://github.com/polkadot-js/apps/issues/144

**Closed by jacogr** 2018-08-24 08:55 UTC
