### ISSUE TITLE
Polkadot.js tab shows camera icon, while camera is off

### ISSUE THREAD

**Issue by anjaw3f** [polkadot-js/apps#3748] opened 2020-09-23 11:53 UTC
There is no QR scan window open in the background which could cause that. 

![Screenshot 2020-09-23 at 13 08 15](https://user-images.githubusercontent.com/70277946/94008823-e6afd100-fda3-11ea-914c-ca3f7cd80649.png)

**Comment by jacogr** [comment] 2020-09-23 12:37
Cannot reproduce.

**Comment by anjaw3f** [comment] 2020-09-23 13:33
Browser is Chrome. 
I tried to reproduce, but no success. It's happened before, but seems random. 
I remember clicking the "Add via QR" button on the accounts page, but then cancelled. This may have caused it, but I can't reproduce that now. 
I know this has happened to other users before. If I encounter it with anyone again I can ask them for more data.

**Comment by jacogr** [comment] 2020-09-26 18:03
Closing. Would love a reproducible case on this. As of now, nothing that can be auctioned.

**Closed by jacogr** 2020-09-26 18:03 UTC
Labels: <support>
