### ISSUE TITLE
Fellowship referenda tab shows wrong links to polkassembly and subsquare

### ISSUE THREAD

**Issue by brenzi** [polkadot-js/apps#8469] opened 2022-12-03 22:12 UTC
- [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
1. go to governance -> fellowship -> referenda
2. click on polkassembly or subsquare buttons for any referendum
3. wrong content shows

It seems subsquare and polkassembly don't even support fellowship referenda so far. but better show no link than a wrong one IMO

**Comment by jacogr** [comment] 2022-12-04 07:42
See https://github.com/polkadot-js/apps/pull/8468

**Comment by jacogr** [comment] 2022-12-06 05:24
Duplicate of PR merged before this was logged. (Was indeed an issue)

**Closed by jacogr** 2022-12-06 05:24 UTC
Labels: <duplicate>
