### ISSUE TITLE
Test accounts not showing in Staking on a local net

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#289] opened 2018-09-06 15:05 UTC
When the UI connect to a local network, the accounts are populated with the test accounts (Alice, Bob, etc...). That is great.
Those accounts however do not show up in Staking.

Workaround is to `add` the account even though there are already there.
That only works until next refresh of the page though.

**Comment by jacogr** [comment] 2018-09-06 15:12
I believe it is wrongly filtered to not show the testing accounts in this case. Exactly how, not 100% sure without looking at it in detail. It really _should_ show up for staking, democracy and "use these accounts" apps. (Double-check on democracy as well)

**Comment by ltfschoen** [comment] 2018-09-17 01:34
@chevdor I'm using macOS 10.13.6 and I just tried to reproduce the issue that you mentioned where you said you can't see the test accounts in the Staking tab http://localhost:3000/#/staking.

I cloned and built the master branch of the Substrate repo.
```
git clone https://github.com/paritytech/substrate;
cd substrate;
git tag -l;
git checkout master;
git remote add upstream https://github.com/paritytech/substrate;
git pull --rebase upstream master;
curl https://sh.rustup.rs -sSf | sh;
rustup update nightly;
rustup target add wasm32-unknown-unknown --toolchain nightly;
rustup update stable;
rustup default stable;
cargo install --git https://github.com/alexcrichton/wasm-gc --force;
cargo install --git https://github.com/pepyakin/wasm-export-table.git --force;
brew install openssl; brew upgrade openssl;
brew install cmake; brew upgrade cmake;
rustc --version; cargo --version;
```

I then tried to run the **Substrate master branch in dev mode**
```
cargo run -- --dev
```
But it generated error: 
```
error: manifest path `paritytech/substrate/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

I then tried the **Substrate v0.2.5 Tag in dev mode**

```
git checkout v0.2.5 -b v0.2.5
./scripts/build.sh; cargo build;
```
It has the build script in the root directory instead of the scripts folder
```
./scripts/build.sh: No such file or directory
```
So I ran the following instead
```
./build.sh; cargo build;
```
But it generated the following errors:
```
     Compiling substrate-rpc-servers v0.1.0 (file:///Users/scon/code/src/paritytech/substrate/substrate/rpc-servers)
  error[E0412]: cannot find type `PendingExtrinsics` in this scope
    --> substrate/rpc-servers/src/lib.rs:50:60
     |
  50 |     A: apis::author::AuthorApi<Block::Hash, Block::Extrinsic, PendingExtrinsics, Metadata=Metadata>,
     |                                                               ^^^^^^^^^^^^^^^^^ not found in this scope

  error[E0244]: wrong number of type arguments: expected 2, found 3
    --> substrate/rpc-servers/src/lib.rs:50:5
     |
  50 |     A: apis::author::AuthorApi<Block::Hash, Block::Extrinsic, PendingExtrinsics, Metadata=Metadata>,
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 type arguments

  error: aborting due to 2 previous errors

  Some errors occurred: E0244, E0412.
  For more information about an error, try `rustc --explain E0244`.
  error: Could not compile `substrate-rpc-servers`.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
```

I then tried the **Substrate v0.2.0 Tag in dev mode**

```
git checkout v0.2.0 -b v0.2.0
./build.sh; cargo build;
./target/debug/polkadot --help;
```

When I ran it **in dev mode with either of the below commands it generated blocks successfully**
```
cargo run -- --dev;
./target/debug/polkadot --dev
```
But when I ran the front-end polkadot-js/apps using the latest master branch it generated error
```
decodeResponse.js?47f7:26 Uncaught (in promise) Error: [-32601]: Method not found
    at checkError (decodeResponse.js?47f7:26)
    at decodeResponse (decodeResponse.js?47f7:34)
    at Object.decodeResponse (index.js?2cc7:24)
    at WsProvider.onSocketMessageResult.response [as onSocketMessageResult] (index.js?4fab:79)
    at WebSocket.WsProvider.onSocketMessage.message (index.js?4fab:63)
```
Although it **didn't generate any blocks when I ran either of the following**, which I thought was equivalent to the above commands
```
cargo run -- --chain=dev;
./target/debug/polkadot --chain=dev
```
It also **didn't generate blocks using local testnet chain specification with Alice and Bob nodes (remembering to copy/paste Alice's bootnode id to run Bob's)** 
```
rm -rf /tmp/alice; rm -rf /tmp/bob;
cargo run -- --chain=local --validator --key Alice -d /tmp/alice;
RUST_LOG=debug RUST_BACKTRACE=1 cargo run -- --chain=local --validator --key Bob -d /tmp/bob --port 30334 --bootnodes 'enode://<INSERT_ALICE_BOOTNODE>@127.0.0.1:30333';
```
Instead it showed the following error in the terminal window of Bob's node:
```
 WARN bft  BFT agreement error: Runtime error
```

I then tried the **Substrate v0.2 Branch (instead of Tags) in dev mode**

```
git fetch upstream v0.2:v0.2;
git checkout v0.2;
./scripts/build.sh; cargo build;
```

When I ran it **in dev mode with either of the below commands it generated blocks successfully**
```
cargo run -- --dev;
./target/debug/polkadot --dev
```
And when I ran the Polkadot-js/apps front-end, it successfully showed all the test accounts including Alice and Bob in the drop-down selection box "using my account" of the Accounts tab http://localhost:3000/#/accounts.

I proceeding to delete all the accounts that were listed in Local Storage, I chose to empty cache and hard reload the browser window, and I clicked "Forget" in the Accounts tab for all the accounts to delete them all. Then I refreshed the browser window and all the test accounts loaded again successfully in Accounts drop-down as shown in this screenshot 

<img width="586" alt="screen shot 2018-09-17 at 11 28 54 am" src="https://user-images.githubusercontent.com/6226175/45603246-94799e00-ba6d-11e8-882f-1287ffeb695a.png">

I performed a query in Chain State > Session > Validators, which returned two validators (Alice and Two), as shown in this screenshot:

<img width="992" alt="screen shot 2018-09-17 at 11 29 38 am" src="https://user-images.githubusercontent.com/6226175/45603250-a2c7ba00-ba6d-11e8-9e77-c41c587f6e7b.png">

And I went to the Staking tab and it displayed both these validators successfully.

<img width="651" alt="screen shot 2018-09-17 at 11 28 24 am" src="https://user-images.githubusercontent.com/6226175/45603252-a9eec800-ba6d-11e8-8943-b9944323b586.png">

Although it **didn't generate any blocks when I ran either of the following**, which I thought was equivalent to the above commands
```
cargo run -- --chain=dev;
./target/debug/polkadot --chain=dev
```
It also **didn't generate blocks using local testnet chain specification with Alice and Bob nodes (remembering to copy/paste Alice's bootnode id to run Bob's)** 

Terminal Tab 1
```
rm -rf /tmp/alice; rm -rf /tmp/bob;
./target/debug/polkadot \
  --chain=local \
  --base-path "/tmp/alice" \
  --execution both \
  --key Alice \
  --keystore-path /root/polkadot/keys \
  --name "ALICE" \
  --node-key "0000000000000000000000000000000000000000000000000000000000000001" \
  --port 30333 \
  --pruning 256 \
  --rpc-external \
  --rpc-port 9933 \
  --telemetry \
  --telemetry-url ws://telemetry.polkadot.io:1024 \
  --validator \
  --ws-external \
  --ws-port 9944
```

Terminal Tab 2
```
RUST_LOG=debug RUST_BACKTRACE=1 \
./target/debug/polkadot \
  --chain=local \
  --base-path "/tmp/bob" \
  --bootnodes '/ip4/127.0.0.1/tcp/30333/p2p/QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN'
  --execution both \
  --key Bob \
  --keystore-path /root/polkadot/keys \
  --name "BOB" \
  --node-key "0000000000000000000000000000000000000000000000000000000000000002" \
  --port 30334 \
  --pruning 256 \
  --rpc-external \
  --rpc-port 9933 \
  --telemetry \
  --telemetry-url ws://telemetry.polkadot.io:1024 \
  --validator \
  --ws-external \
  --ws-port 9944
```

**Comment by jacogr** [comment] 2018-09-17 10:12
Not 100% sure what the above has to do with the UI :) i.e. 

- `error: manifest path `paritytech/substrate/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace` This is 100% correct, substrate master is a library, not an application. It is not runnable.

- `./scripts/build.sh: No such file or directory` - As above. Additionally, as a user of the polkadot apps, it never needs to be run, this is only for runtime devs

Until poc-3, best is to stick with 0.2.x branch. (Additionally if mixing and matching, make sure to remove the dev DB in-between, since polkadot master now uses blake2 for the Trie)

**Comment by ltfschoen** [comment] 2018-10-28 02:09
in the "next" branch (perhaps also in the "master" branch too) it's not showing the test accounts (i.e. Alice, Bob, Ferdie, etc) at all. i did some debugging and found it was because `isDevMode` being is set to `false` when it runs this conditional https://github.com/polkadot-js/apps/blob/master/packages/ui-keyring/src/observable/genericSubject.ts#L26

if i run make the code inside that conditional run, it shows the test accounts, but none of them have any DOTs when using the latest paritytech/substrate "master" and "v0.2" branches  

are we planning to add an option in "Settings" that toggles dev mode on/off?

**Comment by jacogr** [comment] 2018-11-05 07:45
@ltfschoen Next works 100%, I use it exclusively with dev accounts.

The option won't be added to Settings, it creates too much user-related confusion. (Krumme Lanke has DOTs in Alice's account due to users mistakenly using it)

**Comment by jacogr** [comment] 2018-11-05 14:38
Closed in above PR for the next branch. Basically all testing accounts were always filtered when using the specific keyring methods (and inconsistently so as well)

**Closed by jacogr** 2018-11-05 14:38 UTC
Labels: @app-staking, bug
