### ISSUE TITLE
cater for the new slashing storage layout

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#8298] opened 2022-11-01 15:36 UTC
with a lot of delay, https://github.com/paritytech/substrate/pull/11823/files seem to have needed a companion issue here, as it changes the slashing storage layout. For example, as of writing this issue, there is a slash in Kusama that has been deferred, but it is not shown in the slashing page. 

<img width="437" alt="image" src="https://user-images.githubusercontent.com/5588131/199273717-fca0ddfb-83a7-4924-98ff-55641dbefbac.png">
<img width="284" alt="image1" src="https://user-images.githubusercontent.com/5588131/199273724-d44b7396-9875-4a0b-a96a-758bc8b50760.png">
<img width="1728" alt="Screenshot 2022-11-01 at 16 37 29" src="https://user-images.githubusercontent.com/5588131/199273933-0fb44168-5a4a-4b34-9a8b-64a434eabe6d.png">

**Comment by kianenigma** [comment] 2022-11-01 15:42
ahhh -- dupe of https://github.com/polkadot-js/apps/issues/7920. I will leave for you to close, but probably not needed.

**Comment by jacogr** [comment] 2022-11-01 16:50
It doesn’t get picked up because the unapplied index > active. So one of those things where the logic between old and new  just doesn’t work. No idea to solve this to cater for both at this point. May have a gap sometime soon to re-look and re-read the code in Substrate.

**Comment by jacogr** [comment] 2022-11-02 06:00
Closing as duplicate of https://github.com/polkadot-js/apps/issues/7920 (as indicated)

**Closed by jacogr** 2022-11-02 06:00 UTC
Labels: <duplicate>
