### ISSUE TITLE
Support E-Notation

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#224] opened 2018-08-14 16:46 UTC
Since we are still using the base unit, the amounts are often with lots of zero.
It is for those easier and safer to use E-Notation: https://en.wikipedia.org/wiki/Scientific_notation#E-notation

1 Million is easier to write/read/check when written as `1e6` as in `1000000`.

Is `100000` 1 million or not ? (happy counting)

**Comment by jacogr** [comment] 2018-08-15 07:14
Could be useful as an addition in https://github.com/polkadot-js/apps/pull/221 (Since we are doing the number input atm)

**Comment by chevdor** [comment] 2018-08-15 10:35
I did not mention it but this is supported off the shelf by JS:
```
> 1e6 == 1000000
true
```

**Comment by jacogr** [comment] 2018-08-15 17:51
The issue is that with Balances, the normal number inputs break, e.g. https://github.com/polkadot-js/apps/issues/144  - so supporting this is all custom.

(Apart from playing around, we actually had the linked issue logged internally, it is an issue in some case)

**Comment by jacogr** [comment] 2018-10-25 06:02
I believe this is less of an issue (and not as critical) in the "next" branch since you can actually select the denomination, i.e. micro, kilo, M, etc. (Not quite 100% yet since it needs to show the sub-denominations as well, but at least for this specific case it is easier to enter both large and small numbers now)

**Comment by chevdor** [comment] 2018-10-25 08:19
I agree. I would degrade from really nice to have to nice to have :)

**Comment by jacogr** [comment] 2018-12-27 14:00
Closing as non-critical. With the selection of units, there is an alternative solution.

**Closed by jacogr** 2018-12-27 14:00 UTC
Labels: @app-extrinsics, enhancement
