### ISSUE TITLE
If two identical new events occur consecutively, the last one will not be displayed.

### ISSUE THREAD

**Issue by aniiantt** [polkadot-js/apps#4020] opened 2020-11-12 21:57 UTC
https://github.com/polkadot-js/apps/blob/master/packages/react-query/src/Events.tsx#L47-L49

Because the hash of these two events is the same, the latter event is skipped.

So I don't quite understand why the event hash is being compared here. if I delete these two lines, it will work fine.

![image](https://user-images.githubusercontent.com/7029338/99000976-f5925300-259e-11eb-9202-4554e04aa2d0.png)

**Comment by jacogr** [comment] 2020-11-13 07:34
The issue is that blocks can be retracted, that happens 1/4 on Kusama for instance. In that case not doing the compare is worse since duplicate events are displayed. 

So the current implementation the lesser of 2 evils for a summary view.

**Comment by jacogr** [comment] 2020-11-13 18:58
Closing. Sadly not doing this is worse.

**Closed by jacogr** 2020-11-13 18:58 UTC
