### ISSUE TITLE
`ExtError: Expected a valid key to convert, with length 1,2,4,8,32` when using Local Substrate Dev Chain

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#508] opened 2018-12-14 08:36 UTC
Repo Steps:

1. Start a local substrate dev chain
2. Go to Polkadot UI and configure for Local Node
3. Go to Explorer, observe things are working okay
4. Go to Transfer, and submit a transfer from Alice to anyone
5. Go back to Explorer, you should get a white screen with the following error in console:

```
react.f8cba352.js:1 ExtError: Expected a valid key to convert, with length 1,2,4,8,32
    at t.default (https://polkadot.js.org/apps/next/main.a895a981.js:1:194829)
    at t.default (https://polkadot.js.org/apps/next/main.a895a981.js:1:748815)
    at Function.encode (https://polkadot.js.org/apps/next/main.a895a981.js:1:154896)
    at AccountId.toString (https://polkadot.js.org/apps/next/main.a895a981.js:1:155141)
    at t.default (https://polkadot.js.org/apps/next/main.a895a981.js:1:285966)
    at InputAddress.render (https://polkadot.js.org/apps/next/main.a895a981.js:1:109950)
    at lo (https://polkadot.js.org/apps/next/react.f8cba352.js:1:455145)
    at io (https://polkadot.js.org/apps/next/react.f8cba352.js:1:454940)
    at fo (https://polkadot.js.org/apps/next/react.f8cba352.js:1:458630)
    at qo (https://polkadot.js.org/apps/next/react.f8cba352.js:1:473781)
yo @ react.f8cba352.js:1
Oo.n.callback @ react.f8cba352.js:1
ca @ react.f8cba352.js:1
ua @ react.f8cba352.js:1
Ni @ react.f8cba352.js:1
Ii @ react.f8cba352.js:1
Mi @ react.f8cba352.js:1
ji @ react.f8cba352.js:1
Tn @ react.f8cba352.js:1
react.f8cba352.js:1 Uncaught ExtError: Expected a valid key to convert, with length 1,2,4,8,32
    at t.default (https://polkadot.js.org/apps/next/main.a895a981.js:1:194829)
    at t.default (https://polkadot.js.org/apps/next/main.a895a981.js:1:748815)
    at Function.encode (https://polkadot.js.org/apps/next/main.a895a981.js:1:154896)
    at AccountId.toString (https://polkadot.js.org/apps/next/main.a895a981.js:1:155141)
    at t.default (https://polkadot.js.org/apps/next/main.a895a981.js:1:285966)
    at InputAddress.render (https://polkadot.js.org/apps/next/main.a895a981.js:1:109950)
    at lo (https://polkadot.js.org/apps/next/react.f8cba352.js:1:455145)
    at io (https://polkadot.js.org/apps/next/react.f8cba352.js:1:454940)
    at fo (https://polkadot.js.org/apps/next/react.f8cba352.js:1:458630)
    at qo (https://polkadot.js.org/apps/next/react.f8cba352.js:1:473781)
ExtError @ main.a895a981.js:1
t.default @ main.a895a981.js:1
t.default @ main.a895a981.js:1
encode @ main.a895a981.js:1
toString @ main.a895a981.js:1
t.default @ main.a895a981.js:1
render @ main.a895a981.js:1
lo @ react.f8cba352.js:1
io @ react.f8cba352.js:1
fo @ react.f8cba352.js:1
qo @ react.f8cba352.js:1
Yo @ react.f8cba352.js:1
Ii @ react.f8cba352.js:1
Mi @ react.f8cba352.js:1
ji @ react.f8cba352.js:1
Tn @ react.f8cba352.js:1
```

You must refresh the page to get it working again, but all previous blocks are lost.

**Comment by jacogr** [comment] 2018-12-14 08:41
Ok, this one is weird - it normally would show up on master when you are connecting to a local node. However you are using next, so all fine there.

We've seen this once before with Rob, however that just recovered again. And I have not been able to reproduce that one at all.

Could you share your localstorage keys? One has gone wrong in some weird way. (Alternatively since it is in explorer, it could be an unknown or wrongly implemented type). I'm 4 days behind in master, will update to latest as well and see if some type changes has gone it.

**Comment by jacogr** [comment] 2018-12-14 08:49
EDIT: Def. a Transfer event that sees the Account and an AccountId. So the event decoder in api picked up something wrong - and it is not a "new types" issues, events are defined by the runtime itself, so the types should be matching 100%.

**Comment by xlc** [comment] 2018-12-14 10:22
This happens when staking.OfflineSlash events happens, the `InputAddress` field triggers this error.

I am not entirely sure the condition to trigger such event and just using `--dev` chain does triggers it. My custom chain does able to trigger such event frequently.

<img width="1206" alt="screen shot 2018-12-14 at 11 13 45 pm" src="https://user-images.githubusercontent.com/1201310/49997588-dd061080-fff6-11e8-81d3-b6918985ed59.png">

**Comment by jacogr** [comment] 2018-12-14 10:35
Closing based on #509. Confirmed that the fix works on Transfer for me as well. (It should be deployed in 5-10 mins once CI completes)

**Closed by jacogr** 2018-12-14 10:35 UTC
Labels: @app-explorer, bug
