### ISSUE TITLE
Staking should allow multiple nominations + target only stash accounts

### ISSUE THREAD

**Issue by Kianenigma** [polkadot-js/apps#898] opened 2019-04-06 13:07 UTC
The new staking module should 

- Allow you to nominate for multiple accounts
- Optionally: Check via `staking.bonded` that you are nominating for the stash account, not the controller. Almost everyone in the current testnet gets this wrong and fails to nominate properly. 

Optionally to make this really good: 
Note that the stash account is fixed and the controller might change (we actually have a `set_controller` now) so, as opposed to now where controller addresses are displayed in the list and in many places: 
- Show stash account
- Or ideally, make a new component like `AccountPair` that shows both in smaller formate.

There is another issue for it but to recap: 
Generally in staking page `balance` is quite useless to see. display bonded vales everywhere. 

cc @jacogr to assign this properly (@kwingram25 you might be interested as you are working on related stuff) + I might be able to help with staking updates a bit myself if you folks are really overloaded.

**Comment by jacogr** [comment] 2019-04-06 15:23
Nomination in https://github.com/polkadot-js/apps/issues/860

**Comment by jacogr** [comment] 2019-04-06 15:39
The nominating wrong is actually, I believe, caused by a combination of the UI display and where it gets the actual active validators. 

So for the validators, it simply displays `session.validators`, which returns the controllers, not the actual stashes. (Whereas everything in `staking.*`storage refers to stashes)

So the mapping should actually be done to display the linked stashes. (Obviously not an issue through poc-1 to poc-3 since it matched 100% since there were no splits)

**Comment by jacogr** [comment] 2019-04-06 16:56
Closing, issue in #860 (will ref. there)

**Closed by jacogr** 2019-04-06 16:56 UTC
