### ISSUE TITLE
Error: cannot display 20-byte accounts in polkadot.js

### ISSUE THREAD

**Issue by ozgunozerk** [polkadot-js/apps#10995] opened 2024-10-10 14:20 UTC
This is a bug report (may be originating from polkadot.js or maybe originating from our runtime).

As OpenZeppelin, we are building an evm template, and using 20-bytes account due the compatibility reasons with ethereum ecosystem.

  - [x] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

**What is the current behavior and expected behavior?**

As of now, when we try to test our template by deploying a parachain using zombienet, we get the following error in polkadot.js

![image](https://github.com/user-attachments/assets/ca73870b-029c-49df-a43c-e831ea9bfc6f) -> this is from chrome.

Note that, balance transfers, smart contract deployment, etc. everything works. So we are confident that our template is working in terms of functionality. It is also working with metamask and web3js.

**Request and expected behavior**

Expected behavior is to not get the above error and being able to display the accounts correctly. 

We simply want to know whether this is issue is due to our template, or is it something related to polkadot.js. 

As far as we know, Moonbeam also uses 20-byte account types, yet polkadot.js is correctly displaying accounts for them.

Note: for more context, take a look at the relevant PR: https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/326

**Comment by TarikGul** [comment] 2024-10-10 14:58
Some more info would be nice, what tab is this in, and is there a way for us to reproduce it?

**Comment by piggydoughnut** [comment] 2024-10-11 02:41
Hey @ozgunozerk 👋🏽  If you are talking about Identities not being displayed correctly due to that parsing error, then I think this should be resolved shortly once we update the api version in the apps :)

Issues solving the Identity problem are:
apps - https://github.com/polkadot-js/apps/pull/10969
api - https://github.com/polkadot-js/api/pull/5991

Reproduction steps woudl definitely be great 🙌🏽

**Comment by ozgunozerk** [comment] 2024-10-11 05:50
Hi @piggydoughnut and @TarikGul , thanks for the info. Here is the requested detailed steps to reproduce:

following this guide:
https://docs.openzeppelin.com/substrate-runtimes/2.0.1/guides/testing_with_zombienet

on this branch: https://github.com/OpenZeppelin/polkadot-runtime-templates/pull/326/files

Basically, we changed our `chain-spec` to use evm compatible accounts, and after that change, we started to get this error.

@piggydoughnut, which specific release/update should we keep an eye on for this fix?

**Comment by piggydoughnut** [comment] 2024-10-14 13:05
@ozgunozerk If all goes according to the plan you should be all set this week :) I will ping you once we are done.

**Comment by asiniscalchi** [comment] 2024-10-15 07:26
https://github.com/polkadot-js/apps/issues/10954#issuecomment-2413020253

**Comment by piggydoughnut** [comment] 2024-10-16 06:18
@ozgunozerk , I am closing this as it should be resolved by now. Please feel free to re-open in case the issue still arises.

**Closed** 2024-10-16 06:19 UTC
Labels: bug

**Comment by ozgunozerk** [comment] 2024-10-16 07:44
Seems like it is resolved, thanks! 
<img width="1720" alt="image" src="https://github.com/user-attachments/assets/7e9ee7aa-9cba-48a2-a6bc-8ce0f66154de">
