### ISSUE TITLE
Staking Page Missing in Polkadex UI After Latest Changes

### ISSUE THREAD

**Issue by nuel77** [polkadot-js/apps#10505] opened 2024-04-25 06:49 UTC
Hello.

I wanted to bring up an issue that we've noticed in the Polkadex UI after the recent changes from PR #10498 on the polkadot-js/apps repository.

It seems that the staking page section is now missing in Polkadex UI following these updates. I understand that there was a significant change introduced for pallet-staking in the new version, which might have caused this discrepancy.

My main question is whether the apps-ui team has any plans for providing backwards compatibility to address this issue, or if the fix requires upgrading to the latest version of substrate. Understanding the roadmap for resolving this would be immensely helpful for our next steps.

Looking forward to hearing your insights on this matter! 

apps-ui central domain(staking page missing)
<img width="1437" alt="image" src="https://github.com/polkadot-js/apps/assets/50878033/39abb701-5ffb-455c-abb7-2118a54f3557">

apps-ui ipfs doiman (still working)
<img width="1432" alt="image" src="https://github.com/polkadot-js/apps/assets/50878033/3985eae1-65a1-4c5f-b417-a720b9793ed9">

**Comment by kdembler** [comment] 2024-04-25 07:36
Joystream is facing the same issue (`Redirecting from route "/staking" to "/explorer", missing the following APIs: ["query.staking.erasStakersOverview"]`) due to older staking runtime pallet. Hopefully this page could be made backwards compatible, otherwise we will need to host old version of `apps` ourselves.

**Comment by kdembler** [comment] 2024-04-25 07:37
@jacogr @TarikGul

**Comment by TarikGul** [comment] 2024-04-25 14:31
> My main question is whether the apps-ui team has any plans for providing backwards compatibility to address this issue, or if the fix requires upgrading to the latest version of substrate. Understanding the roadmap for resolving this would be immensely helpful for our next steps.

First apologies on any issues this causes. Usually speaking I would aim from the start to ensure backwards compatibility but this specific problem with the new staking changes was a pretty wide net that extended from the `@polkadot/api-derive` package all the way to apps. So it wasn't as simple as providing compatibility in just the UI. Also it's hard to track every chain and what they use, especially when things become urgent.

The compatibility on the api level is the hardest here, as that is where all the observable calls, aggregation, and structuring happens for all the information that the staking UI leverages. 

> Hopefully this page could be made backwards compatible, otherwise we will need to host old version of apps ourselves.

This is never a bad idea.

That all being said, I am OOO for the next week (including today), but when back I will try to look into potential solutions to bring this compatibility solution to a more manageable and maintainable path moving forward. Maybe the best most reasonable solution (for now) is bringing compatibility to the api-derive staking level first, and just make a copy of the old staking page, call it `staking-legacy`, and alias the text to be `staking` in the UI so the experience feels the same.

**Comment by marc-aurele-besner** [comment] 2024-04-28 20:59
In the meantime, anyone can use the [Old IPFS CID](https://ipfs.io/ipfs/QmT5kiADmF3SbsZM3gypZpJMWzheH9aEVdZUdF2exDoxm1/#/staking) 😄

**Comment by PdexFan** [comment] 2024-04-29 05:34
> In the meantime, anyone can use the [Old IPFS CID](https://ipfs.io/ipfs/Qmd5YFzh6CqnJJJyQ9FWYff9SDSP2mmj8oTqgBaQz8uWwV/#/staking) 😄

I can confirm that this solution is not working for Polkadex Main Network.

**Comment by marc-aurele-besner** [comment] 2024-04-30 08:26
> > In the meantime, anyone can use the [Old IPFS CID](https://ipfs.io/ipfs/Qmd5YFzh6CqnJJJyQ9FWYff9SDSP2mmj8oTqgBaQz8uWwV/#/staking) 😄
> 
> I can confirm that this solution is not working for Polkadex Main Network.

I apologize if this solution doesn't help you. An ex-colleague had asked me how to find an old IPFS version on the app due to issues with the current app affecting him on another network, so I thought I would share this link here as well.

For reference, see the [CID Log History](https://github.com/polkadot-js/apps/commits/master/packages/apps/public/ipfs/pin.json)

**Comment by TarikGul** [comment] 2024-05-06 13:57
@nuel77 Just as a heads up I am now tackling this along with fixing staking for the relay chains simultaneously. Hopefully this will all be fixed on the API level today, then I can start tackling the UI bits.

**Comment by MoyStell74** [comment] 2024-05-06 16:38
Good morning everyone, I'm in the same situation, I can't see my goal on the mainet page polkadot.js polkadex network....I trust the team for a prompt update. We are aware
Success

**Comment by MoyStell74** [comment] 2024-05-09 15:11
> La base para la compatibilidad con versiones anteriores se fusionó en la API ayer [polkadot-js/api#5868](https://github.com/polkadot-js/api/pull/5868) . Solo tengo un problema más que abordar en la API para solucionar las recompensas reclamadas con la nueva paleta de apuestas, luego los cambios se publicarán y se reflejarán en las aplicaciones. .

I have been using the polkadex mainnet in polkadot.js for staking since 2021 and for about 3 weeks I have not been able to see the staking section on the network.
I can't make validator changes
I can't add more pdex
I can't withdraw
I can only make transactions with my rewards.
Can you tell me if this is going to be updated or is there another way to enter?
please
thank you

**Comment by TarikGul** [comment] 2024-05-09 15:38
@MoyStell74 Yes, I am currently working on it as we speak: https://github.com/polkadot-js/apps/pull/10553

**Comment by MoyStell74** [comment] 2024-05-09 15:40
> @MoyStell74Sí, actualmente estoy trabajando en ello mientras hablamos: #10553
THANK YOU

**Comment by TarikGul** [comment] 2024-05-09 15:44
@MoyStell74 If you really need to access the staking page for polkadex you can just run `apps` locally, at the commit before the changes.


The commit is ca3f368d47d381e128435ebb6dc587b704940bd1

You just need to pull down apps, and run the following.
```
git checkout ca3f368d47d381e128435ebb6dc587b704940bd1
yarn install && yarn start
```

Then go to `http://localhost:3000/?rpc=wss%3A%2F%2Fpolkadex-mainnet-rpc.dwellir.com#/staking`

And it will work as it previously did.

**Comment by nuel77** [comment] 2024-05-09 16:25
> > La base para la compatibilidad con versiones anteriores se fusionó en la API ayer [polkadot-js/api#5868](https://github.com/polkadot-js/api/pull/5868) . Solo tengo un problema más que abordar en la API para solucionar las recompensas reclamadas con la nueva paleta de apuestas, luego los cambios se publicarán y se reflejarán en las aplicaciones. .
> 
> I have been using the polkadex mainnet in polkadot.js for staking since 2021 and for about 3 weeks I have not been able to see the staking section on the network. I can't make validator changes I can't add more pdex I can't withdraw I can only make transactions with my rewards. Can you tell me if this is going to be updated or is there another way to enter? please thank you

@MoyStell74 you can also try [this ](https://apps.polkagate.xyz/?rpc=wss%3A%2F%2Fpolkadex-mainnet-rpc.dwellir.com#/staking) which is an a old version of the apps UI hosted by the PolkaGate team. if you are facing any emergency use case.

**Comment by TarikGul** [comment] 2024-05-09 18:07
PR is and basically dont to fix the missing staking page: https://github.com/polkadot-js/apps/pull/10557

The tab is the same the only difference is the routing which is now `legacy-staking`

**Comment by TarikGul** [comment] 2024-05-09 18:08
Feel free to test it locally if you would like!

**Comment by TarikGul** [comment] 2024-05-10 00:34
This is now fixed in the live version!

**Closed** 2024-05-10 02:06 UTC

**Comment by nuel77** [comment] 2024-05-10 10:26
Thanks alot @TarikGul 👍
