### ISSUE TITLE
Setting to manually tell Apps to use ethereum-style accounts and signatures

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/apps#9632] opened 2023-06-25 16:06 UTC
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Currently, Apps determines whether to use Ethereum style accounts and signatures by comparing the chain's spec name to a hard-coded list in https://github.com/polkadot-js/apps/blob/e55b9fc67b0dc1f36f2123948fb4a8f18cdc7a38/packages/apps-config/src/settings/ethereumChains.ts#L4

When users are developing chains and first try to switch to Ethereum-style signatures, they regularly become stuck at this step because Apps, the standard manual testing tool, can no longer produce valid signatures. I personally got stuck here, and you can see this question is already asked in stack exchange https://substrate.stackexchange.com/questions/9016/troubleshooting-polkadot-js-recognition-of-prefunded-dev-accounts-on-a-network-u

Ideally, there would be some way that a user could manually tell Apps to use the ethereum style accounts and signatures. For example it could be a checkbox, or require entering some manual types like in the old days.

* **What is the motivation for changing the behavior?**

The motivation is that users regularly get confused and stuck when exploring `AccountId20` compatibility, and it would be nice to point them to a simple setting to make the UI work for them.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment] 2023-06-27 08:38
The issue is as follows -

- these settings only get applied on API connection
- so it will have to be saved and applied on reload of the app
- this means that any chain connected to would get the same settings applied

Basically this means support overhead since developers will forget (like they used to with types) and then have a non-working "normal" environment. And what happens then if they "forget" what they did and log issues, which east up time here.

With the above, this is not something that will make it into the queue of enhancements, but I'm willing to look at PRs. (No promises that it will be merged, but willing to look at the impact, even if it has a very low probability of being accepted)

**Comment by JoshOrndorff** [comment] 2023-06-27 13:10
> support overhead ... developers will forget ... and log issues

Great points. I get what you mean. How do you like this design?

Ethereum signatures are enabled only when the spec name matches the hard-coded list, or a specific url parameter is passed. For example `https://polkadot.js.org/apps/?keyring-type=ethereum`. The setting is not saved or re-applied, so a simple webpage refresh will restore the normal environment to working order.

If this design sounds agreeable, I'll try out a PR. If not, I get it, and feel free to close this issue.

**Comment by jacogr** [comment] 2023-06-28 13:28
That sound perfect.

**Closed** 2023-12-12 06:27 UTC
